services:
  strapi:
    image: node:20-alpine
    container_name: strapi_app
    working_dir: /srv/app
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: "0"
      npm_config_strict_ssl: "false"
    volumes:
      - ./app:/srv/app
    ports:
      - "1337:1337"
    command: sh -c "npm install && npm run develop"

